module.exports = [
  {
    type: "category",
    collapsed: true,
    label: "Get Started",
    items: [
      {
        type: "category",
        collapsed: true,
        label: "Getting Started for PosCreators",
        items: [
          "poscreators/getting-started/get-started",
          "poscreators/getting-started/portal-registration",
        ],
      },
      {
        type: "category",
        collapsed: true,
        label: "Middleware Integration",
        items: [
          "poscreators/getting-started/middleware-integration",
          "poscreators/getting-started/integration-checklist",
        ],
      },
      "poscreators/getting-started/onboarding-posdealers",
    ],
  },
  {
    type: "category",
    collapsed: true,
    label: "fiskaltrust.Middleware",
    items: [
      {
        type: "category",
        label: "General",
        items: [
          "poscreators/middleware-doc/general/general",
          "poscreators/middleware-doc/general/terminology/terminology",
          "poscreators/middleware-doc/general/operation-modes/operation-modes",
          {
            type: "category",
            label: "Components",
            key: "general-components",
            items: [
              "poscreators/middleware-doc/general/components/components",
              "poscreators/middleware-doc/general/components/configuration-components",
            ],
          },
          "poscreators/middleware-doc/general/configuration/configuration",
          "poscreators/middleware-doc/general/receipt-case-definitions/receipt-case-definitions",
        ],
      },
      {
        type: "category",
        label: "Integration",
        collapsed: true,
        key: "integration",
        items: [
          {
            type: "category",
            label: "Cash Register Integration",
            collapsed: true,
            key: "cash-register-integration",
            items: [
              "poscreators/middleware-doc/general/cash-register-integration/cash-register-integration-regular-workflow",
              "poscreators/middleware-doc/general/cash-register-integration/multi-markets-integration-guide",
          {
            type: "category",
            label: "Data Structures",
            collapsed: true,
            key: "data-structures",
            items: [
              "poscreators/middleware-doc/general/data-structures/data-structure-v1",
              "poscreators/middleware-doc/general/data-structures/data-structure-v2",
            ],
          },
          {
            type: "category",
            label: "Reference Tables",
            collapsed: true,
            key: "reference-tables",
            items: [
              "poscreators/middleware-doc/general/reference-tables/reference-tables-v1",
              "poscreators/middleware-doc/general/reference-tables/reference-tables-v2",
            ],
          }
          ],
          },
          "poscreators/middleware-doc/general/function-structures/function-structures",
          "poscreators/middleware-doc/general/communication/communication",
          "poscreators/middleware-doc/general/cash-register-integration/cash-register-integration-failure-scenarios",
        ],
      },
    ],
  },
  {
    type: "category",
    label: "Country-Specific Guides",
    collapsed: true,
    key: "country-specific-guides",
    items: [
      {
        type: "category",
        label: "Austria (AT)",
        items: [
          "poscreators/middleware-doc/middleware-at-rksv/appendix-at-rksv",
          "poscreators/middleware-doc/middleware-at-rksv/terminology/terminology",
          "poscreators/middleware-doc/middleware-at-rksv/operation-modes/operation-modes",
          "poscreators/middleware-doc/middleware-at-rksv/installation/installation",
          "poscreators/middleware-doc/middleware-at-rksv/receipt-case-definitions/receipt-case-definitions",
          "poscreators/middleware-doc/middleware-at-rksv/cash-register-integration/cash-register-integration",
          "poscreators/middleware-doc/middleware-at-rksv/data-structures/data-structures",
          "poscreators/middleware-doc/middleware-at-rksv/reference-tables/reference-tables",
          "poscreators/middleware-doc/middleware-at-rksv/function-structures/function-structures",
          "poscreators/middleware-doc/middleware-at-rksv/communication/communication",
        ],
      },
      {
        type: "category",
        label: "Belgium (BE)",
        items: [
          "poscreators/middleware-doc/middleware-be/appendix-be",
          "poscreators/middleware-doc/middleware-be/terminology/terminology",
          "poscreators/middleware-doc/middleware-be/cash-register-integration/cash-register-integration",
          "poscreators/middleware-doc/middleware-be/data-structures/data-structures",
          {
            type: "category",
            label: "Reference Tables",
            key: "be-reference-tables",
            items: [
              "poscreators/middleware-doc/middleware-be/reference-tables/reference-tables",
              "poscreators/middleware-doc/middleware-be/reference-tables/service-status-ftstate",
              "poscreators/middleware-doc/middleware-be/reference-tables/type-of-receipt-ftreceiptcase",
              "poscreators/middleware-doc/middleware-be/reference-tables/type-of-service-ftchargeitemcase",
              "poscreators/middleware-doc/middleware-be/reference-tables/type-of-payment-ftpayitemcase",
              "poscreators/middleware-doc/middleware-be/reference-tables/type-of-signature-ftsignaturetype",
              "poscreators/middleware-doc/middleware-be/reference-tables/type-of-signature-ftsignatureformat",
              "poscreators/middleware-doc/middleware-be/reference-tables/type-of-journal-ftjournaltype",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Germany (DE)",
        items: [
          "poscreators/middleware-doc/middleware-de-kassensichv/appendix-de-kassensichv",
          "poscreators/middleware-doc/middleware-de-kassensichv/terminology/terminology",
                  {
            type: "category",
            label: "Operation Modes",
            key: "de-operation-modes",
            items: [
              "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/on-premise-installation",
              {
                type: "category",
                label: "On-Premise Platforms",
                key: "de-on-premise-platforms",
                items: [
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/on-premise-platforms/android",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/on-premise-platforms/linux",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/on-premise-platforms/windows",
                ],
              },
              {
                type: "category",
                label: "Signature Creation Devices",
                key: "de-signature-creation-devices",
                items: [
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/scu/a-trust",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/scu/cryptovision",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/scu/deutsche-fiskal",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/scu/diebold-nixdorf",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/scu/epson",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/scu/fiskaly",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/scu/swissbit-cloud",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/scu/swissbit",
                ],
              },
              {
                type: "category",
                label: "On-Premise Databases",
                key: "de-on-premise-databases",
                items: [
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/on-premise-databases/entity-framework",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/on-premise-databases/mysql",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/on-premise-databases/sqlite",
                ],
              },
            ],
          },
          "poscreators/middleware-doc/middleware-de-kassensichv/installation/installation",
          "poscreators/middleware-doc/middleware-de-kassensichv/receipt-case-definitions/receipt-case-definitions",
          {
            type: "category",
            label: "Cash Register Integration",
            key: "de-cash-register-integration",
            items: [
              "poscreators/middleware-doc/middleware-de-kassensichv/cash-register-integration/cash-register-integration",
              "poscreators/middleware-doc/middleware-de-kassensichv/cash-register-integration/single-receipt-creation",
              "poscreators/middleware-doc/middleware-de-kassensichv/cash-register-integration/receipt-sequences-creation",
            ],
          },
          "poscreators/middleware-doc/middleware-de-kassensichv/data-structures/data-structures",
          {
            type: "category",
            label: "Reference Tables",
            key: "de-reference-tables",
            items: [
              "poscreators/middleware-doc/middleware-de-kassensichv/reference-tables/reference-tables",
              "poscreators/middleware-doc/middleware-de-kassensichv/reference-tables/service-status-ftstate",
              "poscreators/middleware-doc/middleware-de-kassensichv/reference-tables/type-of-receipt-ftreceiptcase",
              "poscreators/middleware-doc/middleware-de-kassensichv/reference-tables/type-of-service-ftchargeitemcase",
              "poscreators/middleware-doc/middleware-de-kassensichv/reference-tables/type-of-payment-ftpayitemcase",
              "poscreators/middleware-doc/middleware-de-kassensichv/reference-tables/type-of-signature-ftsignaturetype",
              "poscreators/middleware-doc/middleware-de-kassensichv/reference-tables/type-of-signature-ftsignatureformat",
              "poscreators/middleware-doc/middleware-de-kassensichv/reference-tables/type-of-journal-ftjournaltype",
            ],
          },
          "poscreators/middleware-doc/middleware-de-kassensichv/procedural-documentation/dsfinv-k-generation",
        ],
      },
      {
        type: "category",
        label: "Spain (ES)",
        items: [
          "poscreators/middleware-doc/middleware-es/appendix-es",
          "poscreators/middleware-doc/middleware-es/terminology/terminology",
          "poscreators/middleware-doc/middleware-es/cash-register-integration/cash-register-integration",
          "poscreators/middleware-doc/middleware-es/data-structures/data-structures",
          {
            type: "category",
            label: "Reference Tables",
            key: "es-reference-tables",
            items: [
              "poscreators/middleware-doc/middleware-es/reference-tables/reference-tables",
              "poscreators/middleware-doc/middleware-es/reference-tables/service-status-ftstate",
              "poscreators/middleware-doc/middleware-es/reference-tables/type-of-receipt-ftreceiptcase",
              "poscreators/middleware-doc/middleware-es/reference-tables/type-of-service-ftchargeitemcase",
              "poscreators/middleware-doc/middleware-es/reference-tables/type-of-payment-ftpayitemcase",
              "poscreators/middleware-doc/middleware-es/reference-tables/type-of-signature-ftsignaturetype",
              "poscreators/middleware-doc/middleware-es/reference-tables/type-of-signature-ftsignatureformat",
              "poscreators/middleware-doc/middleware-es/reference-tables/type-of-journal-ftjournaltype",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "France (FR)",
        items: [
          "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/appendix-fr-boi-tva-decla-30-10-30",
          "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/terminology/terminology",
          "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/operation-modes/operation-modes",
          "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/installation/installation",
          "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/receipt-case-definitions/receipt-case-definitions",
          {
            type: "category",
            label: "Cash Register Integration",
            key: "fr-cash-register-integration",
            items: [
              "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/cash-register-integration/cash-register-integration",
              "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/cash-register-integration/failure-scenario",
            ],
          },
          "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/data-structures/data-structures",
          "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/reference-tables/reference-tables",
          "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/function-structures/function-structures",
          "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/communication/communication",
        ],
      },
      {
        type: "category",
        label: "Greece (GR)",
        items: [
          "poscreators/middleware-doc/middleware-gr/appendix-gr",
          "poscreators/middleware-doc/middleware-gr/terminology/terminology",
          "poscreators/middleware-doc/middleware-gr/cash-register-integration/cash-register-integration",
          "poscreators/middleware-doc/middleware-gr/data-structures/data-structures",
          {
            type: "category",
            label: "Reference Tables",
            key: "gr-reference-tables",
            items: [
              "poscreators/middleware-doc/middleware-gr/reference-tables/reference-tables",
              "poscreators/middleware-doc/middleware-gr/reference-tables/service-status-ftstate",
              "poscreators/middleware-doc/middleware-gr/reference-tables/type-of-receipt-ftreceiptcase",
              "poscreators/middleware-doc/middleware-gr/reference-tables/type-of-service-ftchargeitemcase",
              "poscreators/middleware-doc/middleware-gr/reference-tables/type-of-payment-ftpayitemcase",
              "poscreators/middleware-doc/middleware-gr/reference-tables/type-of-signature-ftsignaturetype",
              "poscreators/middleware-doc/middleware-gr/reference-tables/type-of-signature-ftsignatureformat",
              "poscreators/middleware-doc/middleware-gr/reference-tables/type-of-journal-ftjournaltype",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Italy (IT)",
        items: [
          "poscreators/middleware-doc/middleware-it-registratore-telematico/appendix-it-registratore-telematico",
          "poscreators/middleware-doc/middleware-it-registratore-telematico/terminology/terminology",
                   {
            type: "category",
            label: "Operation Modes",
            key: "it-operation-modes",
            items: [
              "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/installation",
              {
                type: "category",
                label: "On-Premise Platforms",
                key: "it-on-premise-platforms",
                items: [
                  "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/on-premise-platforms/linux",
                  "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/on-premise-platforms/windows",
                ],
              },
              {
                type: "category",
                label: "On-Premise Databases",
                key: "it-on-premise-databases",
                items: [
                  "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/on-premise-databases/sqlite",
                  "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/on-premise-databases/entity-framework",
                  "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/on-premise-databases/mysql",
                ],
              },
              {
                type: "category",
                label: "Signature Creation Devices",
                key: "it-signature-creation-devices",
                items: [
                  "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/scu/epsonprinter",
                  "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/scu/customprinter",
                  "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/scu/customserver",
                  "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/scu/ivaservizi",
                ],
              },
            ],
          }, 
          "poscreators/middleware-doc/middleware-it-registratore-telematico/installation/installation",
          "poscreators/middleware-doc/middleware-it-registratore-telematico/receipt-case-definitions/receipt-case-definitions",
          "poscreators/middleware-doc/middleware-it-registratore-telematico/cash-register-integration/cash-register-integration",
          "poscreators/middleware-doc/middleware-it-registratore-telematico/data-structures/data-structures",
          {
            type: "category",
            label: "Reference Tables",
            key: "it-reference-tables",
            items: [
              "poscreators/middleware-doc/middleware-it-registratore-telematico/reference-tables/reference-tables",
              "poscreators/middleware-doc/middleware-it-registratore-telematico/reference-tables/service-status-ftstate",
              "poscreators/middleware-doc/middleware-it-registratore-telematico/reference-tables/type-of-receipt-ftreceiptcase",
              "poscreators/middleware-doc/middleware-it-registratore-telematico/reference-tables/type-of-service-ftchargeitemcase",
              "poscreators/middleware-doc/middleware-it-registratore-telematico/reference-tables/type-of-payment-ftpayitemcase",
              "poscreators/middleware-doc/middleware-it-registratore-telematico/reference-tables/type-of-signature-ftsignaturetype",
              "poscreators/middleware-doc/middleware-it-registratore-telematico/reference-tables/type-of-signature-ftsignatureformat",
              "poscreators/middleware-doc/middleware-it-registratore-telematico/reference-tables/type-of-journal-ftjournaltype",
            ],
          },
          "poscreators/middleware-doc/middleware-it-registratore-telematico/communication/communication",
        ],
      },
      {
        type: "category",
        label: "Portugal (PT)",
        items: [
          "poscreators/middleware-doc/middleware-pt/appendix-pt",
          "poscreators/middleware-doc/middleware-pt/terminology/terminology",
          "poscreators/middleware-doc/middleware-pt/cash-register-integration/cash-register-integration",
          "poscreators/middleware-doc/middleware-pt/data-structures/data-structures",
          {
            type: "category",
            label: "Reference Tables",
            key: "pt-reference-tables",
            items: [
              "poscreators/middleware-doc/middleware-pt/reference-tables/reference-tables",
              "poscreators/middleware-doc/middleware-pt/reference-tables/service-status-ftstate",
              "poscreators/middleware-doc/middleware-pt/reference-tables/type-of-receipt-ftreceiptcase",
              "poscreators/middleware-doc/middleware-pt/reference-tables/type-of-service-ftchargeitemcase",
              "poscreators/middleware-doc/middleware-pt/reference-tables/type-of-payment-ftpayitemcase",
              "poscreators/middleware-doc/middleware-pt/reference-tables/type-of-signature-ftsignaturetype",
              "poscreators/middleware-doc/middleware-pt/reference-tables/type-of-signature-ftsignatureformat",
              "poscreators/middleware-doc/middleware-pt/reference-tables/type-of-journal-ftjournaltype",
            ],
          },
        ],
      },
    ],
  },
  {
    type: "category",
    collapsed: true,
    label: "InStore App",
    items: [
      "poscreators/middleware-doc/instore-app/introduction/introduction",
      "poscreators/middleware-doc/instore-app/available-settings/settings",
      "poscreators/middleware-doc/instore-app/Setup-guide/setup",
            {
        type: "category",
        label: "Installation Guides",
        items: [
          "poscreators/middleware-doc/instore-app/installation-guides/installation-guides",
          "poscreators/middleware-doc/instore-app/installation-guides/manual/manual-guide",
          "poscreators/middleware-doc/instore-app/installation-guides/GooglePlay/googleplay-guide",
          "poscreators/middleware-doc/instore-app/installation-guides/Orderman/orderman-guide",
          "poscreators/middleware-doc/instore-app/installation-guides/Sunmi/sunmi-guide",
        ],
      },
      "poscreators/middleware-doc/instore-app/printer-guide/printer",
      "poscreators/middleware-doc/instore-app/multiterminal-settings/multiterminal",
    ],
  },
  {
    type: "link",
    label: "Development Kit",
    href: "https://github.com/fiskaltrust/possystemapi-devkit/blob/main/README.MD",
  },
];
