module.exports = [
  {
    type: "category",
    label: "Get Started",
    items: [
      {
        type: "category",
        label: "Getting Started for PosCreators",
        items: [
          "poscreators/getting-started/get-started",
          "poscreators/getting-started/portal-registration",
        ],
      },
      {
        type: "category",
        label: "Middleware Integration",
        items: [
          "poscreators/getting-started/middleware-integration",
          "poscreators/getting-started/integration-checklist",
        ],
      },
      "poscreators/getting-started/onboarding-posdealers",
    ],
  },
  {
    type: "category",
    collapsed: false,
    label: "Middleware API documentation",
    items: [
      {
        type: "category",
        label: "General",
        items: [
          "poscreators/middleware-doc/general/general",
          "poscreators/middleware-doc/general/terminology/terminology",
          {
            type: "category",
            label: "Cash register integration",
            items: [
              "poscreators/middleware-doc/general/cash-register-integration/cash-register-integration-regular-workflow",
              "poscreators/middleware-doc/general/cash-register-integration/cash-register-integration-failure-scenarios",
              "poscreators/middleware-doc/general/cash-register-integration/multi-markets-integration-guide",
            ],
          },
          "poscreators/middleware-doc/general/data-structures/data-structures",
          "poscreators/middleware-doc/general/function-structures/function-structures",
          "poscreators/middleware-doc/general/communication/communication",
          {
            type: "category",
            label: "Operation modes",
            key: "general-operation-modes",
            items: [
              "poscreators/middleware-doc/general/operation-modes/operation-modes",
              "poscreators/middleware-doc/general/operation-modes/configuration",
            ],
          },
          "poscreators/middleware-doc/general/installation/installation",
          "poscreators/middleware-doc/general/receipt-case-definitions/receipt-case-definitions",
          "poscreators/middleware-doc/general/reference-tables/reference-tables",
        ],
      },
      {
        type: "category",
        label: "Austria (RKSV)",
        items: [
          "poscreators/middleware-doc/middleware-at-rksv/appendix-at-rksv",
          "poscreators/middleware-doc/middleware-at-rksv/terminology/terminology",
          "poscreators/middleware-doc/middleware-at-rksv/cash-register-integration/cash-register-integration",
          "poscreators/middleware-doc/middleware-at-rksv/data-structures/data-structures",
          "poscreators/middleware-doc/middleware-at-rksv/function-structures/function-structures",
          "poscreators/middleware-doc/middleware-at-rksv/communication/communication",
          "poscreators/middleware-doc/middleware-at-rksv/operation-modes/operation-modes",
          "poscreators/middleware-doc/middleware-at-rksv/installation/installation",
          "poscreators/middleware-doc/middleware-at-rksv/receipt-case-definitions/receipt-case-definitions",
          "poscreators/middleware-doc/middleware-at-rksv/reference-tables/reference-tables",
        ],
      },
      {
        type: "category",
        label: "Belgium (Closed Beta)",
        items: [
          "poscreators/middleware-doc/middleware-be/appendix-be",
          "poscreators/middleware-doc/middleware-be/terminology/terminology",
          "poscreators/middleware-doc/middleware-be/cash-register-integration/cash-register-integration",
          "poscreators/middleware-doc/middleware-be/data-structures/data-structures",
          {
            type: "category",
            label: "Reference Tables",
            key: "be-reference-tables",
            items: [
              "poscreators/middleware-doc/middleware-be/reference-tables/reference-tables",
              "poscreators/middleware-doc/middleware-be/reference-tables/service-status-ftstate",
              "poscreators/middleware-doc/middleware-be/reference-tables/type-of-receipt-ftreceiptcase",
              "poscreators/middleware-doc/middleware-be/reference-tables/type-of-service-ftchargeitemcase",
              "poscreators/middleware-doc/middleware-be/reference-tables/type-of-payment-ftpayitemcase",
              "poscreators/middleware-doc/middleware-be/reference-tables/type-of-signature-ftsignaturetype",
              "poscreators/middleware-doc/middleware-be/reference-tables/type-of-signature-ftsignatureformat",
              "poscreators/middleware-doc/middleware-be/reference-tables/type-of-journal-ftjournaltype",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Germany (KassenSichV)",
        items: [
          "poscreators/middleware-doc/middleware-de-kassensichv/appendix-de-kassensichv",
          "poscreators/middleware-doc/middleware-de-kassensichv/terminology/terminology",
          "poscreators/middleware-doc/middleware-de-kassensichv/installation/installation",
          {
            type: "category",
            label: "Cash register integration",
            key: "de-cash-register-integration",
            items: [
              "poscreators/middleware-doc/middleware-de-kassensichv/cash-register-integration/cash-register-integration",
              "poscreators/middleware-doc/middleware-de-kassensichv/cash-register-integration/single-receipt-creation",
              "poscreators/middleware-doc/middleware-de-kassensichv/cash-register-integration/receipt-sequences-creation",
            ],
          },
          "poscreators/middleware-doc/middleware-de-kassensichv/data-structures/data-structures",
          {
            type: "category",
            label: "Operation modes",
            key: "de-operation-modes",
            items: [
              "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/on-premise-installation",
              {
                type: "category",
                label: "On-premise platforms",
                key: "de-on-premise-platforms",
                items: [
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/on-premise-platforms/android",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/on-premise-platforms/linux",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/on-premise-platforms/windows",
                ],
              },
              {
                type: "category",
                label: "Signature Creation Devices",
                key: "de-signature-creation-devices",
                items: [
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/scu/a-trust",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/scu/cryptovision",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/scu/deutsche-fiskal",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/scu/diebold-nixdorf",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/scu/epson",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/scu/fiskaly",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/scu/swissbit-cloud",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/scu/swissbit",
                ],
              },
              {
                type: "category",
                label: "On-premise databases",
                key: "de-on-premise-databases",
                items: [
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/on-premise-databases/entity-framework",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/on-premise-databases/mysql",
                  "poscreators/middleware-doc/middleware-de-kassensichv/operation-modes/on-premise-databases/sqlite",
                ],
              },
            ],
          },
          {
            type: "category",
            label: "Reference Tables",
            key: "de-reference-tables",
            items: [
              "poscreators/middleware-doc/middleware-de-kassensichv/reference-tables/reference-tables",
              "poscreators/middleware-doc/middleware-de-kassensichv/reference-tables/service-status-ftstate",
              "poscreators/middleware-doc/middleware-de-kassensichv/reference-tables/type-of-receipt-ftreceiptcase",
              "poscreators/middleware-doc/middleware-de-kassensichv/reference-tables/type-of-service-ftchargeitemcase",
              "poscreators/middleware-doc/middleware-de-kassensichv/reference-tables/type-of-payment-ftpayitemcase",
              "poscreators/middleware-doc/middleware-de-kassensichv/reference-tables/type-of-signature-ftsignaturetype",
              "poscreators/middleware-doc/middleware-de-kassensichv/reference-tables/type-of-signature-ftsignatureformat",
              "poscreators/middleware-doc/middleware-de-kassensichv/reference-tables/type-of-journal-ftjournaltype",
            ],
          },
          "poscreators/middleware-doc/middleware-de-kassensichv/receipt-case-definitions/receipt-case-definitions",
          "poscreators/middleware-doc/middleware-de-kassensichv/procedural-documentation/dsfinv-k-generation",
        ],
      },
      {
        type: "category",
        label: "Spain (Open Beta)",
        items: [
          "poscreators/middleware-doc/middleware-es/appendix-es",
          "poscreators/middleware-doc/middleware-es/terminology/terminology",
          "poscreators/middleware-doc/middleware-es/cash-register-integration/cash-register-integration",
          "poscreators/middleware-doc/middleware-es/data-structures/data-structures",
          {
            type: "category",
            label: "Reference Tables",
            key: "es-reference-tables",
            items: [
              "poscreators/middleware-doc/middleware-es/reference-tables/reference-tables",
              "poscreators/middleware-doc/middleware-es/reference-tables/service-status-ftstate",
              "poscreators/middleware-doc/middleware-es/reference-tables/type-of-receipt-ftreceiptcase",
              "poscreators/middleware-doc/middleware-es/reference-tables/type-of-service-ftchargeitemcase",
              "poscreators/middleware-doc/middleware-es/reference-tables/type-of-payment-ftpayitemcase",
              "poscreators/middleware-doc/middleware-es/reference-tables/type-of-signature-ftsignaturetype",
              "poscreators/middleware-doc/middleware-es/reference-tables/type-of-signature-ftsignatureformat",
              "poscreators/middleware-doc/middleware-es/reference-tables/type-of-journal-ftjournaltype",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "France (BOI-TVA-DECLA-30-10-30)",
        items: [
          "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/appendix-fr-boi-tva-decla-30-10-30",
          "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/terminology/terminology",
          {
            type: "category",
            label: "Cash register integration",
            key: "fr-cash-register-integration",
            items: [
              "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/cash-register-integration/cash-register-integration",
              "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/cash-register-integration/failure-scenario",
            ],
          },
          "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/data-structures/data-structures",
          "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/function-structures/function-structures",
          "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/communication/communication",
          "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/operation-modes/operation-modes",
          "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/installation/installation",
          "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/receipt-case-definitions/receipt-case-definitions",
          "poscreators/middleware-doc/middleware-fr-boi-tva-decla-30-10-30/reference-tables/reference-tables",
        ],
      },
      {
        type: "category",
        label: "Greece (Closed Beta)",
        items: [
          "poscreators/middleware-doc/middleware-gr/appendix-gr",
          "poscreators/middleware-doc/middleware-gr/terminology/terminology",
          "poscreators/middleware-doc/middleware-gr/cash-register-integration/cash-register-integration",
          "poscreators/middleware-doc/middleware-gr/data-structures/data-structures",
          {
            type: "category",
            label: "Reference Tables",
            key: "gr-reference-tables",
            items: [
              "poscreators/middleware-doc/middleware-gr/reference-tables/reference-tables",
              "poscreators/middleware-doc/middleware-gr/reference-tables/service-status-ftstate",
              "poscreators/middleware-doc/middleware-gr/reference-tables/type-of-receipt-ftreceiptcase",
              "poscreators/middleware-doc/middleware-gr/reference-tables/type-of-service-ftchargeitemcase",
              "poscreators/middleware-doc/middleware-gr/reference-tables/type-of-payment-ftpayitemcase",
              "poscreators/middleware-doc/middleware-gr/reference-tables/type-of-signature-ftsignaturetype",
              "poscreators/middleware-doc/middleware-gr/reference-tables/type-of-signature-ftsignatureformat",
              "poscreators/middleware-doc/middleware-gr/reference-tables/type-of-journal-ftjournaltype",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Italy (Registratore Telematico)",
        items: [
          "poscreators/middleware-doc/middleware-it-registratore-telematico/appendix-it-registratore-telematico",
          "poscreators/middleware-doc/middleware-it-registratore-telematico/terminology/terminology",
          "poscreators/middleware-doc/middleware-it-registratore-telematico/installation/installation",
          "poscreators/middleware-doc/middleware-it-registratore-telematico/cash-register-integration/cash-register-integration",
          "poscreators/middleware-doc/middleware-it-registratore-telematico/communication/communication",
          "poscreators/middleware-doc/middleware-it-registratore-telematico/data-structures/data-structures",
          {
            type: "category",
            label: "Operation modes",
            key: "it-operation-modes",
            items: [
              "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/installation",
              {
                type: "category",
                label: "On-premise platforms",
                key: "it-on-premise-platforms",
                items: [
                  "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/on-premise-platforms/linux",
                  "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/on-premise-platforms/windows",
                ],
              },
              {
                type: "category",
                label: "Signature Creation Devices",
                key: "it-signature-creation-devices",
                items: [
                  "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/scu/epsonprinter",
                  "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/scu/customprinter",
                  "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/scu/customserver",
                  "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/scu/ivaservizi",
                ],
              },
              {
                type: "category",
                label: "On-premise databases",
                key: "it-on-premise-databases",
                items: [
                  "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/on-premise-databases/sqlite",
                  "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/on-premise-databases/entity-framework",
                  "poscreators/middleware-doc/middleware-it-registratore-telematico/operation-modes/on-premise-databases/mysql",
                ],
              },
            ],
          },
          {
            type: "category",
            label: "Reference Tables",
            key: "it-reference-tables",
            items: [
              "poscreators/middleware-doc/middleware-it-registratore-telematico/reference-tables/reference-tables",
              "poscreators/middleware-doc/middleware-it-registratore-telematico/reference-tables/service-status-ftstate",
              "poscreators/middleware-doc/middleware-it-registratore-telematico/reference-tables/type-of-receipt-ftreceiptcase",
              "poscreators/middleware-doc/middleware-it-registratore-telematico/reference-tables/type-of-service-ftchargeitemcase",
              "poscreators/middleware-doc/middleware-it-registratore-telematico/reference-tables/type-of-payment-ftpayitemcase",
              "poscreators/middleware-doc/middleware-it-registratore-telematico/reference-tables/type-of-signature-ftsignaturetype",
              "poscreators/middleware-doc/middleware-it-registratore-telematico/reference-tables/type-of-signature-ftsignatureformat",
              "poscreators/middleware-doc/middleware-it-registratore-telematico/reference-tables/type-of-journal-ftjournaltype",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Portugal (Closed Beta)",
        items: [
          "poscreators/middleware-doc/middleware-pt/appendix-pt",
          "poscreators/middleware-doc/middleware-pt/terminology/terminology",
          "poscreators/middleware-doc/middleware-pt/cash-register-integration/cash-register-integration",
          "poscreators/middleware-doc/middleware-pt/data-structures/data-structures",
          {
            type: "category",
            label: "Reference Tables",
            key: "pt-reference-tables",
            items: [
              "poscreators/middleware-doc/middleware-pt/reference-tables/reference-tables",
              "poscreators/middleware-doc/middleware-pt/reference-tables/service-status-ftstate",
              "poscreators/middleware-doc/middleware-pt/reference-tables/type-of-receipt-ftreceiptcase",
              "poscreators/middleware-doc/middleware-pt/reference-tables/type-of-service-ftchargeitemcase",
              "poscreators/middleware-doc/middleware-pt/reference-tables/type-of-payment-ftpayitemcase",
              "poscreators/middleware-doc/middleware-pt/reference-tables/type-of-signature-ftsignaturetype",
              "poscreators/middleware-doc/middleware-pt/reference-tables/type-of-signature-ftsignatureformat",
              "poscreators/middleware-doc/middleware-pt/reference-tables/type-of-journal-ftjournaltype",
            ],
          },
        ],
      },
    ],
  },
  {
    type: "category",
    collapsed: false,
    label: "Digital Receipt",
    items: [
      "poscreators/middleware-doc/digital-receipt/Introduction/digital-receipt-introduction",
      {
        type: "category",
        label: "General",
        key: "digital-receipt-general",
        items: [
          "poscreators/middleware-doc/digital-receipt/General/receive-receipts",
          "poscreators/middleware-doc/digital-receipt/General/bundles",
          "poscreators/middleware-doc/digital-receipt/General/compliance",
          "poscreators/middleware-doc/digital-receipt/Instore-App/digital-receipt-instore-app",
          {
            type: "category",
            label: "Implementation",
            items: [
              "poscreators/middleware-doc/digital-receipt/implementation/getting-started",
              "poscreators/middleware-doc/digital-receipt/implementation/digital-receipt-implementation",
            ],
          },
        ],
      },
    ],
  },
  {
    type: "category",
    collapsed: false,
    label: "InStore App",
    items: [
      "poscreators/middleware-doc/instore-app/Introduction/digital-receipt-introduction",
      "poscreators/middleware-doc/instore-app/available-settings/settings",
      "poscreators/middleware-doc/instore-app/Setup-guide/setup",
      "poscreators/middleware-doc/instore-app/printer-guide/printer",
      "poscreators/middleware-doc/instore-app/multiterminal-settings/multiterminal",
      "poscreators/middleware-doc/instore-app/installation-guides/installation-guides",
      {
        type: "category",
        label: "Installation Guides",
        items: [
          "poscreators/middleware-doc/instore-app/installation-guides/manual/manual-guide",
          "poscreators/middleware-doc/instore-app/installation-guides/GooglePlay/googleplay-guide",
          "poscreators/middleware-doc/instore-app/installation-guides/Orderman/orderman-guide",
          "poscreators/middleware-doc/instore-app/installation-guides/Sunmi/sunmi-guide",
        ],
      },
    ],
  },
  {
    type: "link",
    label: "Middleware API samples",
    href: "https://middleware-samples.docs.fiskaltrust.cloud/",
  },
  {
    type: "category",
    collapsed: false,
    label: "Receipt signing APIs",
    items: [
      {
        type: "category",
        label: "RKSV.Sign (Austria)",
        items: [
          "poscreators/middleware-doc/signing-at-rksv/rksv-sign-intro",
          "poscreators/middleware-doc/signing-at-rksv/rksv-sign-api",
          {
            type: "link",
            label: "RKSV.Sign API samples",
            href: "https://rksvsign-samples.docs.fiskaltrust.cloud/",
          },
        ],
      },
    ],
  },
];
