// old
// const poscreators = require("./poscreators/toc.js");
// const posdealers = require("./posdealers/toc.js");
// module.exports = {
//   poscreators,
//   posdealers,
// };

module.exports = {
  faq: ["faq/roles", "faq/terms"],
  poscreators: [
    {
      type: "autogenerated",
      dirName: "./poscreators",
    },
  ],
  posdealers: [
    {
      type: "autogenerated",
      dirName: "./posdealers",
    },
  ],
};
